export const GenModel = {  
    
    tokenName:  'anyGoods_token',
    tokenMenus:  'tokenMenus',
    tokenExpiryTime: 'tokenExpiryTime',
    tokenCheckTimeInterval: 'tokenCheckTimeInterval',
    loginStatus: 'loginStatus',
    accountNumberFormat: '',
    maxLengthFormat: 0,
    userId: 'userId', 
    btnConfirm: '#c62828',
    fineAddedd: 'fineAddedd',
    payStackKey: '',
    subaccount: '',
    retryService: 5,
    retryDelayServiceInterval: 1000,
    internetConMsg: `Low or Bad Internet Connection`,
    userLoginInfo: 'userLoginInfo',
    role: 'role',
    pageLmit: 10,
    recordDetails: 'recordDetails',
    appHeader: 'appHeader',
    errorOccur: `Your Request Couldn't be Processed. Kindly Try Later`,
    apiIsDown: `Your Request took longer than Expected. Kindly Try Later`,
    redirectUrl: 'redirectUrl',
    loginRoleId: 'loginRoleId',
    hideLoginBack: 'hideLoginBack',
    RetryAttmMsg: 'Retrying...Attempt',
    ActionHeaderMsg: 'ADD NEW',
    ActionEditHeaderMsg: 'EDIT',
    ActionViewHeaderMsg: 'DETAILS',
    requiredFieldMsg: 'Fields with Red Borders are required',
    UserId: 'UserId',
    RoleId: 'RoleId',
    userDetails: 'userDetails',
    userMenu: 'userMenu',
    userLoginType: 'userLoginType',
    LoderTimer: 50,
    EncryptKey: 'EncryptKey',
    selectTransMsg : 'Select Record(s)!',
    recordNotFoundMsg : `Your Search Criteria Could'nt be found!`,
    cbsOfflineMsg: "Core Banking is on Offline Mode, Kindly Contact the System Admin",
    noMandateMsg: 'No Mandate found for this Account',
    approveFromServiceMsg: 'Are you Sure you want to Approve this Request(s)?',
    noMorePrevRec: 'No more Previous Record',
    noMoreNextRec: 'No more Next Record',
    acctmaxLengthDefault: 20,

    delimeter: '',
    GlDelimeter: '-',
    Version: 'v2022.0.0.2',
    broadCastMsg: 'broadCastMsg',
    txtAreaMaxLengthDefault: '200',
};  


